- name: check-spelling
  id: spelling
  uses: check-spelling/check-spelling@v0.0.24
  with:
    suppress_push_for_open_pull_request: 1
    checkout: true
    post_comment: 0
    extra_dictionary_limit: 10
    extra_dictionaries:
      cspell:software-terms/software-terms.txt
      cspell:php/php.txt
      cspell:node/node.txt
      cspell:django/django.txt
      cspell:html/html.txt
      cspell:npm/npm.txt
      cspell:ruby/ruby.txt
      cspell:fullstack/fullstack.txt
      cspell:filetypes/filetypes.txt
    check_extra_dictionaries: ''
    dictionary_source_prefixes: >-
      {"cspell": "https://raw.githubusercontent.com/check-spelling/cspell-dicts/v20241114/dictionaries/"}
    spell_check_file_extensions: .md .markdown
